version: '3'
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile_php_apache/Dockerfile"
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  db:
    image: jacobalberty/firebird:2.5.9-ss
    expose:
      - 3050